import { Mode } from "./types/types";

export const ModesMock: Mode[] = [
  {
    id: 1,
    name: "Classic",
    description: "Class mode for party games with friends and family members",
    image: "https://i.imgur.com/",
    isFree: true,
    purchased: false,
    type: "default",
  },
  {
    id: 2,
    name: "Super play",
    description: "Class mode for party games with friends and family members",
    image: "https://i.imgur.com/",
    isFree: false,
    purchased: false,
    type: "default",
  },
  {
    id: 3,
    name: "Cool mode!",
    description: "Class mode for party games with friends and family members",
    image: "https://i.imgur.com/",
    isFree: false,
    purchased: false,
    type: "default",
  },
  {
    id: 4,
    name: "After night mode",
    description: "Class mode for party games with friends and family members",
    image: "https://i.imgur.com/",
    isFree: false,
    purchased: false,
    type: "default",
  },
  {
    id: 5,
    name: "Drinking mode",
    description: "Class mode for party games with friends and family members",
    image: "https://i.imgur.com/",
    isFree: false,
    purchased: false,
    type: "default",
  },
  {
    id: 6,
    name: "The best mode",
    description: "Class mode for party games with friends and family members",
    image: "https://i.imgur.com/",
    isFree: false,
    purchased: false,
    type: "default",
  },
];
